module.exports = {
  ONE_SECOND: 1000,
  majorTomCommandStates: [
    'preparing_on_gateway',
    'uplinking_to_system',
    'transmitted_to_system',
    'acked_by_system',
    'executing_on_system',
    'downlinking_from_system',
    'processing_on_gateway',
    'cancelled',
    'completed',
    'failed',
  ],
  majorTomGatewayManagerStates: [
    'received_from_mt',
    'preparing_on_gateway',
    'gateway_prep_complete',
    'ready_for_system',
    'uplinking_to_system',
    'transmitted_to_system',
    'acked_by_system',
    'executing_on_system',
    'downlinking_from_system',
    'done_on_system',
    'processing_on_gateway',
    'complete_on_gateway',
    'cancel_on_gateway',
    'cancelled',
    'completed',
    'failed',
  ],
};